[package]
name = "cluster"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
aes = "0.8.4"
dashmap.workspace = true
lazy_static.workspace = true
shared = { path = "../shared" }
tokio.workspace = true
