[package]
name = "sustenet-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = { workspace = true }
base64.workspace = true
config = { workspace = true }
ctrlc = { workspace = true }
tokio = { version = "1.41.1", features = ["sync"] }
