[package]
name = "sustenet-client"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
lazy_static.workspace = true
shared = { package = "sustenet-shared", path = "../shared" }
tokio.workspace = true
