[package]
name = "sustenet"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
num_cpus = "1.16.0"
quaternion = "2.0.0"
tokio = { version = "1.40.0", features = [
  "socket2",
  "macros",
  "rt-multi-thread",
  "net",
  "sync",
  "io-util",
] }
vector3 = "1.1.4"
