[package]
name = "master"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
dashmap.workspace = true
getrandom.workspace = true
lazy_static.workspace = true
shared = { path = "../shared" }
tokio.workspace = true
